# Settings apply to all build contexts
[build]
  # Default Storybook output directory
  publish = "storybook-static"

  # Default Storybook static build command
  command = "npm run build-storybook"

  # Without this, Storybook's necessary devDependencies may not install. We
  # could move those to full dependencies, but most of those dependencies are
  # not necessary for projects consuming this library, so that would be silly.
  NODE_ENV = "development"
